version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    exclude-group:
      exclude-patterns:
        - .github/workflows/exclude-*.yml
    applies-to-group:
      applies-to: version-updates
